name: skorch_env
channels:
  - pytorch
  - defaults
dependencies:
  - scikit-learn
  - pytorch
  - torchvision
  - pip
  - jupyterlab
  - seaborn
  - tqdm
  - matplotlib
  - pip:
    - skorch==0.6.0
    - kaggle==1.5.4
